sudo: required

env:
  global:
    - DOCKER_IMAGE_NAME=cv

language: node_js
node_js:
  - '11'

services:
  - docker

before_script:
  - yarn

script:
  - make

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $DOCKER_IMAGE_NAME:latest whomenope/cv:latest

deploy:
  - provider: script
    script: docker push whomenope/cv:latest
    skip_cleanup: true
    on:
      branch: master
