sudo: required

env:
  global:
    - DOCKER_IMAGE_NAME=cv
    - TAG=latest

language: node_js
node_js:
  - '11'

services:
  - docker

before_script:
  - yarn

script:
  - yarn build
  - docker image build -t $DOCKER_IMAGE_NAME:$TAG .

before_deploy:
  - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  - docker tag $DOCKER_IMAGE_NAME:$TAG $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$TAG

deploy:
  - provider: script
    script: docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$TAG
    skip_cleanup: true
    on:
      branch: master
